- name: Remove APT Packages
  apt:
    name: "{{ rempackages }}"
    state: absent
  vars:
    rempackages:
      - geary
      - fish
      - libreoffice-*
      - docker
      - docker-engine
      - docker.io
      - ibus
      - plank
- name: Autoremove and Purge APT Packages
  apt:
    autoremove: yes
    purge: yes
- name: Install APT Packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - neovim
      - xclip
      - tmux
      - openssh-server
      - ubuntu-restricted-extras
      - debconf-utils
      - htop
      - budgie-*-applet
      - gnome-mpv
      - whois
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
      - python-pip
      - snapd-xdg-open
      - rtv
      - breeze-icon-theme
      - breeze-gtk-theme
      - breeze-cursor-theme
      - grub-theme-breeze
      - asciinema
      - unzip
      - tar
      - htop
      - tilix
      - python3-pip
      - build-essential
      - python-dev
      - cmake
      - software-properties-common
      - ack

- name: Autoremove and Purge APT Packages
  apt:
    autoremove: yes
    purge: yes
