- name: Adding System Users
  user:
    name: bjk
    comment: Brian Ketelsen
    shell: /bin/bash
    groups: sudo, adm, cdrom, dip, plugdev, lpadmin, sambashare, docker, lxd
    append: yes
- name: Install GH SSH Pub keys
  authorized_key:
    user: "{{ myusername }}"
    state: present
    key: https://github.com/{{item}}.keys
  with_items:
      - bketelsen
- name: Fixing SSH Key Permissions
  become: yes
  file:
    path: "/home/{{ myusername }}/.ssh/"
    recurse: yes
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700
- name: Fixing SSH Key Permissions
  become: yes
  file:
    path: "/home/{{ myusername }}/.ssh/id_rsa"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0600
- name: Fixing SSH Key Permissions
  become: yes
  file:
    path: "/home/{{ myusername }}/.ssh/id_rsa.pub"
    owner: "{{  myusername }}"
    group: "{{ myusername }}"
    mode: 0600
